---
- name: Ensure Administrator password is valid
  ansible.windows.win_user:
    name: '{{ domain_info.domain_admin.username }}'
    password: '{{ domain_info.domain_admin.password }}'
    state: present

- name: Ensure the domain exists
  win_domain:
    domain_netbios_name: '{{ domain_info.netbios_name }}'
    dns_domain_name: '{{ domain_info.domain_name }}'
    safe_mode_password: '{{ domain_info.safe_mode_password }}'
  register: domain_res
  retries: 5
  delay: 25
  until: domain_res is not failed

- name: Reboot after domain was created
  win_reboot:
    reboot_timeout: 900
    post_reboot_delay: 100
  when: domain_res.changed

- name: Ensure the server is a domain controller
  win_domain_controller:
    dns_domain_name: '{{ domain_info.domain_name }}'
    domain_admin_user: '{{ domain_info.domain_admin.username }}@{{ domain_info.domain_name }}'
    domain_admin_password: '{{ domain_info.domain_admin.password }}'
    safe_mode_password: '{{ domain_info.safe_mode_password }}'
    state: domain_controller
  register: check_domain_controller

- name: Reboot to complete domain controller setup
  win_reboot:
    reboot_timeout: 900
    post_reboot_delay: 100
  when: check_domain_controller.changed
