{% if 'rbac' in network and 'identities' in network.rbac  %}
# Autogenerated RBAC identities
    {% for key, value in network.rbac.identities.items() %}
resource "azurerm_user_assigned_identity" "{{ key }}" {
resource_group_name = azurerm_resource_group.resource_group_sincity.name
location            = "{{ config.region }}"
name                = "{{ key }}"
}
    {% endfor %}
# End of autogenerated RBAC identities
{% endif %}

{% if 'rbac' in network and 'roles' in network.rbac  %}
# Autogenerated RBAC roles
    {% for key, value in network.rbac.roles.items() %}
resource "azurerm_role_definition" "{{ key }}" {
  name        = "{{ key }}"
  scope       = "/subscriptions/{{ config.subscription_id }}"
  description = "{{ value.description | default('') }}"

  permissions {
    actions     = {{ value.permissions.actions | default([]) | to_terraform_array('', '', True) | safe }}
    not_actions = {{ value.permissions.not_actions | default([]) | to_terraform_array('', '', True) | safe }}
  }

  assignable_scopes = {{ value.assignable_scopes | to_terraform_array('azurerm_user_assigned_identity', 'id') | safe }}
}
# End of autogenerated RBAC roles
    {% endfor %}
{% endif %}