---
- name: setup-ous
  import_tasks: setup-ous.yml
  when: domain_info.ous is defined
  tags: ad-ous

- name: domain-groups
  import_tasks: domain-groups.yml
  tags: ad-groups

- name: users
  import_tasks: domain-users.yml
  tags: ad-users

- name: setup-gpos
  import_tasks: setup-gpos.yml
  when: domain_info.gpos is defined
  tags: ad-gpos
