---
- name: Install prerequisites
  yum:
    name: conntrack
  become: yes

- name: Install cri-dockerd
  shell: |
    # Download cri-dockerd
    wget https://github.com/Mirantis/cri-dockerd/releases/download/v0.2.0/cri-dockerd-v0.2.0-linux-amd64.tar.gz
    tar xvf cri-dockerd-v0.2.0-linux-amd64.tar.gz

    # Save the binary onto the linux
    sudo mv ./cri-dockerd /usr/local/bin/ 

    # Download the services
    wget https://raw.githubusercontent.com/Mirantis/cri-dockerd/master/packaging/systemd/cri-docker.service
    wget https://raw.githubusercontent.com/Mirantis/cri-dockerd/master/packaging/systemd/cri-docker.socket

    # Move the services to their appropriate locations
    sudo mv cri-docker.socket cri-docker.service /etc/systemd/system/
    sudo sed -i -e 's,/usr/bin/cri-dockerd,/usr/local/bin/cri-dockerd,' /etc/systemd/system/cri-docker.service

    # Now enable the daemon and services
    systemctl daemon-reload
    systemctl enable cri-docker.service
    systemctl enable --now cri-docker.socket

- name: Install crictl
  shell: |
    # Install crictl
    VERSION="v1.24.1"
    wget https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-$VERSION-linux-amd64.tar.gz
    sudo tar zxvf crictl-$VERSION-linux-amd64.tar.gz -C /usr/bin
    rm -f crictl-$VERSION-linux-amd64.tar.gz

  become: yes

- name: Install kubectl
  tags: kubectl
  shell: |
    # Download and install kubectl
    cd /tmp
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

  become: yes

- name: Install minikube
  tags: minikube
  shell: |
    # Download minikube
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm

    # Install minikube
    sudo rpm -Uvh minikube-latest.x86_64.rpm

    # Now start minikube
    minikube start --driver=none

  become: yes